name: envTest2
on:
  workflow_dispatch:
  
jobs:  
  run-test-windows: 
    runs-on: windows-latest
    steps:
      - name: Set color
        id: random-color-generator
        run: |
          echo "SELECTED_COLOR=blue" >> $env:GITHUB_OUTPUT
          echo "SELECTED_COLOR=blue" >> $env:GITHUB_ENV
        
      - name: Get color
        run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
          echo "The selected color is ${{ env.SELECTED_COLOR }}"

  run-test-ubunto: 
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: random-color-generator
        run: |
          echo "SELECTED_COLOR=blue" >> $GITHUB_OUTPUT
          echo "SELECTED_COLOR=blue" >> $GITHUB_ENV
        
      - name: Get color
        run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
          echo "The selected color is ${{ env.SELECTED_COLOR }}"
        
  useENV: 
    runs-on: windows-latest
    needs: [run-test-windows, run-test-ubunto]
    steps:      
      - name: Get color
        run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
          echo "The selected color is ${{ env.SELECTED_COLOR }}"
