name: Manual workflow
on:
  workflow_dispatch:

  
jobs:  
  get-data: 
    runs-on: ubuntu-latest
    outputs:
      solutions: "[1, 2, 3, 4]"
    steps: 
      - name: first
        run: echo test

  example_matrix:
    needs: [get-data]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution: ${{ fromJson(needs.get-data.outputs.solutions) }}
    steps:
      - name: WriteIt
        run: echo ${{ matrix.solution}}
