name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
        branchName:
          # Default value if no value is explicitly provided
          default: 'newBranch'
          # Input has to be provided for the workflow to run
          required: true

jobs:
  prepareBranch:
    runs-on: ubuntu-latest
    
    env: 
      newBranchName: workflow/${{github.event.inputs.branchName}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create branch
      run: git checkout -b ${{env.newBranchName}}; git push --set-upstream origin ${{env.newBranchName}}
      
    - name: Create pull request
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{ "title": "Pull PP changes", "head": "${{env.newBranchName}}", "base": "main", "body": "This is the pull request body", "labels": ["enhancement", "bug"] }' https://api.github.com/repos/${{ github.repository }}/pulls
