name: Manual workflow
on:
  workflow_dispatch:

jobs:
  prepareBranch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download release artifact
      run: |
        curl -s https://api.github.com/repos/andersgMSFT/powerAppsTest/releases/latest | grep "browser_download_url" | grep "1.7 - BcSampleAppsSolution(QA).zip" | cut -d '"' -f 4

    - name: List files in folder
      run: |
        ls -la
