name: Manual workflow
on:
  workflow_dispatch:

jobs:
  prepareBranch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download release artifact 
      run: .github\actions\script\gitGetReleaseArtifact.ps1 

    - name: List files in folder
      run: |
        ls -la
