name: Manual workflow
on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution: [sol.zip, sol2.zip]
    steps:
      - name: WriteIt
        run: echo ${{ matrix.solution}}
