name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
        branchName:
          # Default value if no value is explicitly provided
          default: 'newBranch'
          # Input has to be provided for the workflow to run
          required: true

jobs:
  prepareBranch:
    runs-on: ubuntu-latest
    
    env: 
      newBranchName: workflow/${{github.event.inputs.branchName}};

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create branch
      run: git checkout -b ${{env.newBranchName}} git push --set-upstream origin ${{env.newBranchName}}
      
    - name: Create pull request
      run: |
        hub pull-request -b main -h my-new-branch -m "Pull latest changes from <insert name>" -l "update app"
