name: ENV Test workflow
on:
  workflow_dispatch:
  
jobs:  
  JobName:
    runs-on: ubuntu-latest
    steps: 
      - name: first
        run: echo test
        
      - name: findSolutionFile
        shell: ${{inputs.shell}}
        run: |
            $file = "anderstestpath.zip";
            Write-Host "Found match:"$file;
            Add-Content -Path $env:GITHUB_OUTPUT -Value "powerPlatformSolutionPath=$file";
            echo "{powerPlatformSolutionPath}={$file}" >> $GITHUB_ENV
              
      - name: Unpack solution artifact
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ env.powerPlatformSolutionPath }}
          solution-folder: test.zip
          solution-type: "Unmanaged"
          overwrite-files: true
          process-canvas-apps: true
