name: ENV Test workflow
on:
  workflow_dispatch:
  
jobs:  
  JobName:
    runs-on: windows-latest
    steps: 
     
      - name: findSolutionFile
        shell: powershell
        run: |
            $file = "anderstestpath/path";
            Write-Host "Found match:"$file;
            echo "powerPlatformSolutionPath=$file" >> $env:GITHUB_ENV
      
      - name: Use the value
        shell: powershell
        run: |
          echo "${{ env.powerPlatformSolutionPath }}"
                 
      - name: Unpack solution artifact
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ env.powerPlatformSolutionPath }}
          solution-folder: test.zip
          solution-type: "Unmanaged"
          overwrite-files: true
          process-canvas-apps: true
