name: ENV Test workflow
on:
  workflow_dispatch:
  
jobs:  
  JobName:
    runs-on: windows-latest
    steps: 

        
      - name: findSolutionFile
        shell: powershell
        run: |
            $file = "anderstestpath.zip";
            Write-Host "Found match:"$file;
            Add-Content -Path $env:GITHUB_OUTPUT -Value "powerPlatformSolutionPath=$file";
            echo "{powerPlatformSolutionPath}={$file}" >> $GITHUB_ENV

      - name: findSolutionFile2
        shell: powershell
        run: |
            $authContext = "anderstestpath.zip";
            Add-Content -Path $env:GITHUB_OUTPUT -Value "authContext=$authContext"
            Write-Host "authContext=$authContext"
             
      - name: Unpack solution artifact
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ steps.findSolutionFile2.outputs.authContext }}
          solution-folder: test.zip
          solution-type: "Unmanaged"
          overwrite-files: true
          process-canvas-apps: true
