name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
        branchName:
          # Default value if no value is explicitly provided
          default: 'newBranch'
          # Input has to be provided for the workflow to run
          required: true

jobs:
  prepareBranch:
    runs-on: ubuntu-latest
    
    env: 
      newBranchName: workflow/${{github.event.inputs.branchName}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download release artifact
      run: |
        ARTIFACT_URL=$(curl -s https://api.github.com/repos/andersgMSFT/powerAppsTest/releases/latest | grep "browser_download_url" | grep "1.7 - BcSampleAppsSolution(QA).zip" | cut -d '"' -f 4)
        curl -LJO# "$ARTIFACT_URL"

    - name: List files in folder
      run: |
        ls -la
