name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
        branchName:
          # Default value if no value is explicitly provided
          default: 'newBranch'
          # Input has to be provided for the workflow to run
          required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Create branch
      run: git checkout -b workflow/${github.events.inputs.branchName}; git push 
